Tracker:AddLocations("locations/ASH.json")
Tracker:AddLocations("locations/BFM.json")
Tracker:AddLocations("locations/Black Knight Arena.json")
Tracker:AddLocations("locations/BoG.json")
Tracker:AddLocations("locations/CC.json")
Tracker:AddLocations("locations/CD.json")
Tracker:AddLocations("locations/CR.json")
Tracker:AddLocations("locations/Crimean Nursing Graveyard.json")
Tracker:AddLocations("locations/DM.json")
Tracker:AddLocations("locations/DS.json")
Tracker:AddLocations("locations/Deep Sea Knight Area.json")
Tracker:AddLocations("locations/Deserted Road.json")
Tracker:AddLocations("locations/Endless Tea Party.json")
Tracker:AddLocations("locations/Erebus.json")
Tracker:AddLocations("locations/FF.json")
Tracker:AddLocations("locations/Florence Arena.json")
Tracker:AddLocations("locations/GotH.json")
Tracker:AddLocations("locations/IF.json")
Tracker:AddLocations("locations/Jabberwocks Lair.json")
Tracker:AddLocations("locations/Jubjubs Nest.json")
Tracker:AddLocations("locations/LC.json")
Tracker:AddLocations("locations/LD.json")
Tracker:AddLocations("locations/LT.json")
Tracker:AddLocations("locations/MV.json")
Tracker:AddLocations("locations/MW.json")
Tracker:AddLocations("locations/Madness Mountain.json")
Tracker:AddLocations("locations/NF.json")
Tracker:AddLocations("locations/ORS.json")
Tracker:AddLocations("locations/OWU.json")
Tracker:AddLocations("locations/PoBT.json")
Tracker:AddLocations("locations/PoF.json")
Tracker:AddLocations("locations/QL.json")
Tracker:AddLocations("locations/RCF.json")
Tracker:AddLocations("locations/RGC.json")
Tracker:AddLocations("locations/RH.json")
Tracker:AddLocations("locations/SCT.json")
Tracker:AddLocations("locations/SF.json")
Tracker:AddLocations("locations/SG.json")
Tracker:AddLocations("locations/SH.json")
Tracker:AddLocations("locations/Snow Field.json")
Tracker:AddLocations("locations/ULT.json")
Tracker:AddLocations("locations/White Castletown.json")
Tracker:AddLocations("locations/Windless Valley.json")
Tracker:AddLocations("locations/Winterbell.json")
Tracker:AddLocations("locations/Overworld.json")
